version: '3'
services:
  unifi-video-controller:
    build: .
    ports:
      - 1935:1935
      - 6666:6666
      - 7004:7004
      - 7080:7080
      - 7442:7442
      - 7443:7443
      - 7444:7444
      - 7445:7445
      - 7446:7446
      - 7447:7447
    volumes:
      - data:/var/lib/unifi-video
      - video:/var/lib/unifi-video/videos
    environment:
      - TZ=Europe/Berlin
      - DEBUG=1
      - CREATE_TMPFS=no
volumes:
  data:
  video:
